Repository DDD-Community/DDD-11-Dissonance-iOS, pull requests merged in 2025-05, with the labels that each got.

#70 [ITDS - 80] feature: 해커톤 -> 교육 카테고리 변경
  Targets/DataLayer/Sources/RequestDTO/PostListFetchRequestDTO.swift
  Targets/DesignSystem/Sources/Component/PostUpload/PostCategoryView.swift
  Targets/DomainLayer/Sources/Entities/PostKind.swift
  Targets/DomainLayer/Sources/Entities/PostUploadCategory.swift
  Targets/MozipCore/Sources/GA.swift
  Targets/PresentationLayer/Sources/Home/Reactor/HomeReactor.swift
  Targets/PresentationLayer/Sources/Home/View/HomeViewController.swift
Labels: 리팩토링

#71 [ITDS-81] feature: 홈 화면 공고셀 북마크 정보노출, 북마크리스트 화면 구현
  Targets/DataLayer/Sources/APIs/UserAPI.swift
  Targets/DataLayer/Sources/Repositories/UserRepository.swift
  Targets/DataLayer/Sources/Responses/PostCellResponse.swift
  Targets/DataLayer/Sources/Responses/User/BookmarkListResponse.swift
  Targets/DataLayer/Sources/Responses/User/BookmarkResponse.swift
  Targets/DesignSystem/Resources/Assets.xcassets/bookmark.imageset/Contents.json
  Targets/DesignSystem/Resources/Assets.xcassets/bookmark.imageset/bookmark.png
  Targets/DesignSystem/Resources/Assets.xcassets/bookmarkCountIcon.imageset/Contents.json
  Targets/DesignSystem/Resources/Assets.xcassets/bookmarkCountIcon.imageset/bookmarkCountIcon.png
  Targets/DesignSystem/Sources/Component/BookmarkList/BookmarkCell.swift
  Targets/DesignSystem/Sources/Component/Home/HomeNavigationBar.swift
  Targets/DesignSystem/Sources/Component/Home/PostCell.swift
  Targets/DomainLayer/Sources/Entities/BookmarkCellData.swift
  Targets/DomainLayer/Sources/Entities/PostCellData.swift
  Targets/DomainLayer/Sources/Interfaces/UserRepositoryType.swift
  Targets/DomainLayer/Sources/UseCases/UserUseCase.swift
  Targets/MozipCore/Sources/GA.swift
  Targets/PresentationLayer/Sources/BookmarkList/Coordinator/BookmarkListCoordinator.swift
  Targets/PresentationLayer/Sources/BookmarkList/Reactor/BookmarkListReactor.swift
  Targets/PresentationLayer/Sources/BookmarkList/View/BookmarkListViewController.swift
  Targets/PresentationLayer/Sources/Home/Coordinator/HomeCoordinator.swift
  Targets/PresentationLayer/Sources/Home/View/HomeViewController.swift
  Targets/PresentationLayer/Sources/PresentationAssembly.swift
Labels: 기능 구현

#75 [ITDS-84] bug: 로그인 상태에 따른 접근 권환 관련 버그 수정
  Targets/PresentationLayer/Sources/Home/View/HomeViewController.swift
  Targets/PresentationLayer/Sources/PostDetail/View/PostDetailViewController.swift
Labels: 버그 수정

#76 [ITDS-85] hotfix: 공고 수정 버그 수정
  Targets/DataLayer/Sources/Responses/Post/PostEditResponse.swift
  Targets/DomainLayer/Sources/Entities/Post.swift
  Targets/DomainLayer/Sources/UseCases/PostUploadUseCase.swift
  Targets/MozipCore/Sources/DateFormatterUtil.swift
  Targets/MozipCore/Sources/Extensions/DateFormatter+.swift
  Targets/MozipCore/Sources/PropertyBuilder.swift
  Targets/MozipCore/Sources/PropertyBuilderCompatible.swift
  Targets/PresentationLayer/Sources/PostUpload/Coordinator/PostUploadCoordinator.swift
Labels: 버그 수정
