Repository DDD-Community/DDD-11-Dissonance-iOS, pull requests merged in 2025-06, with the labels that each got.

#87 qa: 오류사항 대응
  Targets/DomainLayer/Sources/Entities/Post.swift
  Targets/PresentationLayer/Sources/PostDetail/Coordinator/PostDetailCoordinator.swift
  Targets/PresentationLayer/Sources/PostDetail/Reactor/PostDetailReactor.swift
  Targets/PresentationLayer/Sources/PostDetail/View/PostDetailViewController.swift
  Targets/PresentationLayer/Sources/PostUpload/Coordinator/PostUploadCoordinator.swift
  Targets/PresentationLayer/Sources/PostUpload/View/PostUploadViewController.swift
Labels: 버그 수정

#90 [ITDS-90] refactor: 공고 리스트 오류해결 및 페이징 기능추가
  Targets/DataLayer/Sources/Repositories/PostRepository.swift
  Targets/DataLayer/Sources/Responses/PostCellResponse.swift
  Targets/DomainLayer/Sources/Entities/PostPage.swift
  Targets/DomainLayer/Sources/Interfaces/PostRepositoryType.swift
  Targets/DomainLayer/Sources/UseCases/FetchPostListUseCase.swift
  Targets/DomainLayer/Sources/UseCases/SearchPostListUseCase.swift
  Targets/PresentationLayer/Sources/Home/Reactor/HomeReactor.swift
  Targets/PresentationLayer/Sources/Home/View/HomeViewController.swift
  Targets/PresentationLayer/Sources/PostList/Reactor/PostListReactor.swift
  Targets/PresentationLayer/Sources/PostList/View/PostListViewController.swift
  Targets/PresentationLayer/Sources/PostSearch/Reactor/PostSearchReactor.swift
Labels: 버그 수정, 기능 구현

#93 [ITDS-91] refactor: 공고 업로드 오류 수정 및 코드 품질 개선
  Targets/DataLayer/Sources/Responses/Post/PostDetailResponse.swift
  Targets/DesignSystem/Sources/Component/PostUpload/ImageUploadView.swift
  Targets/DesignSystem/Sources/Component/PostUpload/LabelWithTextView.swift
  Targets/DomainLayer/Sources/Entities/Post.swift
  Targets/PresentationLayer/Sources/PostDetail/Reactor/PostDetailReactor.swift
  Targets/PresentationLayer/Sources/PostDetail/View/PostDetailViewController.swift
  Targets/PresentationLayer/Sources/PostUpload/Coordinator/PostUploadCoordinator.swift
  Targets/PresentationLayer/Sources/PostUpload/Reactor/PostUploadReactor.swift
  Targets/PresentationLayer/Sources/PostUpload/View/PostUploadViewController.swift
Labels: 버그 수정, 리팩토링
